#Use the Official python image as base image
FROM python:3.11

#Set environment variables for Python
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /app
COPY . .

# Install dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Expose port 8000 to allow external connections to this port
EXPOSE 8000

# Run Django app
CMD ["python", "manage.py","runserver","0.0.0.0:8000"]