# Use an official Python runtime as the base image
FROM python3.10-alpine

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app



# Copy the requirements file to the container
COPY ./App/requirements.txt  /app/

# Install the project dependencies
RUN pip install --no-cache-dir -r requirements.txt